import {
  LINKED_PROVIDER_STATUSES,
  PASSPORT_STATUSES,
  VERIFIED_PROOF_STATUSES,
} from './constants.js';

export const PASSPORT_STATUS_TRANSITIONS = Object.freeze({
  [PASSPORT_STATUSES.DRAFT_PRIVATE]: [
    PASSPORT_STATUSES.PUBLISHED,
    PASSPORT_STATUSES.UNPUBLISHED,
    PASSPORT_STATUSES.SUSPENDED,
  ],
  [PASSPORT_STATUSES.PUBLISHED]: [
    PASSPORT_STATUSES.UNPUBLISHED,
    PASSPORT_STATUSES.SUSPENDED,
  ],
  [PASSPORT_STATUSES.UNPUBLISHED]: [
    PASSPORT_STATUSES.PUBLISHED,
    PASSPORT_STATUSES.DRAFT_PRIVATE,
    PASSPORT_STATUSES.SUSPENDED,
  ],
  [PASSPORT_STATUSES.SUSPENDED]: [
    PASSPORT_STATUSES.UNPUBLISHED,
  ],
});

export const LINKED_PROVIDER_STATUS_TRANSITIONS = Object.freeze({
  [LINKED_PROVIDER_STATUSES.PENDING]: [
    LINKED_PROVIDER_STATUSES.VERIFIED,
    LINKED_PROVIDER_STATUSES.FAILED,
    LINKED_PROVIDER_STATUSES.REVOKED,
  ],
  [LINKED_PROVIDER_STATUSES.VERIFIED]: [
    LINKED_PROVIDER_STATUSES.STALE,
    LINKED_PROVIDER_STATUSES.REVOKED,
  ],
  [LINKED_PROVIDER_STATUSES.FAILED]: [
    LINKED_PROVIDER_STATUSES.PENDING,
    LINKED_PROVIDER_STATUSES.REVOKED,
  ],
  [LINKED_PROVIDER_STATUSES.STALE]: [
    LINKED_PROVIDER_STATUSES.PENDING,
    LINKED_PROVIDER_STATUSES.VERIFIED,
    LINKED_PROVIDER_STATUSES.REVOKED,
  ],
  [LINKED_PROVIDER_STATUSES.REVOKED]: [
    LINKED_PROVIDER_STATUSES.PENDING,
  ],
});

export const VERIFIED_PROOF_STATUS_TRANSITIONS = Object.freeze({
  [VERIFIED_PROOF_STATUSES.CURRENT]: [
    VERIFIED_PROOF_STATUSES.STALE,
    VERIFIED_PROOF_STATUSES.REVOKED,
  ],
  [VERIFIED_PROOF_STATUSES.STALE]: [
    VERIFIED_PROOF_STATUSES.CURRENT,
    VERIFIED_PROOF_STATUSES.REVOKED,
  ],
  [VERIFIED_PROOF_STATUSES.REVOKED]: [],
});

function canTransition(map, from, to) {
  return Boolean(map[from]?.includes(to));
}

export function canTransitionPassportStatus(from, to) {
  return canTransition(PASSPORT_STATUS_TRANSITIONS, from, to);
}

export function canTransitionLinkedProviderStatus(from, to) {
  return canTransition(LINKED_PROVIDER_STATUS_TRANSITIONS, from, to);
}

export function canTransitionVerifiedProofStatus(from, to) {
  return canTransition(VERIFIED_PROOF_STATUS_TRANSITIONS, from, to);
}
