import React from 'react';
import { Helmet } from 'react-helmet';
import { Link } from 'react-router-dom';
import AdPlaceholder from './AdPlaceholder.jsx';

const GamerBioSEOContent = () => {
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "What makes a good gamer bio?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "A good gamer bio is concise, reflects your personality or playstyle, and clearly states your main games. It should use formatting like line breaks, emojis, or symbols to stand out and be easy to read on platforms like Discord or Twitch."
        }
      },
      {
        "@type": "Question",
        "name": "Can I use special characters in my bio?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Yes! Most modern platforms (Discord, Instagram, Twitch, TikTok) fully support Unicode special characters and symbols. Using stars (★), lightning bolts (⚡), or custom fonts can make your bio look much more aesthetic."
        }
      },
      {
        "@type": "Question",
        "name": "What are the best bios for Discord?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Discord bios look best when they are formatted with line breaks. A popular format is listing your main game, your rank/status, and a short funny or tryhard quote. Keep it under 190 characters to ensure it displays fully."
        }
      },
      {
        "@type": "Question",
        "name": "How do I make my bio stand out?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "To make your bio stand out, avoid generic phrases. Use our generator to combine unique tones (like Dark or Aesthetic) with cool symbols. You can also use our Stylish Text Generator to change the actual font of your bio text."
        }
      },
      {
        "@type": "Question",
        "name": "Can I use emojis on all platforms?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Almost all social and gaming platforms support standard emojis. However, some older in-game profile systems might not render them correctly. If you're putting a bio directly inside a game client, it's safer to stick to text symbols."
        }
      },
      {
        "@type": "Question",
        "name": "What is the ideal length for a gaming bio?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "The ideal length depends on the platform. Twitter/X and Instagram are best with short to medium bios (50-100 characters). Twitch panels can be much longer. Discord bios should be punchy, around 2-3 short lines."
        }
      },
      {
        "@type": "Question",
        "name": "Are there any restrictions on gamer bios?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Always follow the Terms of Service of the platform you are using. Avoid hate speech, excessive profanity, or inappropriate links, as these can get your account banned on platforms like Twitch or Discord."
        }
      },
      {
        "@type": "Question",
        "name": "How often should I change my bio?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "It's a good idea to update your bio whenever your main game changes, you hit a new rank, or you join a new clan/esports team. Keeping it fresh shows your profile is active."
        }
      },
      {
        "@type": "Question",
        "name": "What are trending bios in 2026?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "In 2026, minimalist aesthetic bios and highly formatted 'tryhard' bios are trending. Players love using clean borders (╔══ ══╗) and subtle symbols (✦, 🌙) rather than cluttering their bio with too many emojis."
        }
      },
      {
        "@type": "Question",
        "name": "Can I use these bios on Twitch or YouTube?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Absolutely! The medium and long bios generated by our tool are perfect for Twitch 'About Me' panels or your YouTube channel description. They help new viewers instantly understand what your channel is about."
        }
      }
    ]
  };

  return (
    <>
      <Helmet>
        <script type="application/ld+json">
          {JSON.stringify(faqSchema)}
        </script>
      </Helmet>

      <section className="max-w-4xl mx-auto py-16 space-y-16">
        <div className="prose prose-invert max-w-none space-y-6">
          <p className="text-lg text-foreground/90 leading-relaxed">
            Your bio is the first read when someone opens Discord, Twitch, or your in-game profile. A flat line reads anonymous; a tight, aesthetic, or tryhard line signals intent. Use this lane to sample captions and bios you can tune to your games, tone, and formatting—then paste what fits.
          </p>
        </div>

        <article className="space-y-4">
          <h2 className="text-3xl font-bold text-primary">Cool Gamer Bios</h2>
          <p className="text-foreground/90 leading-relaxed">
            A cool gamer bio doesn't try too hard. It's effortless, clean, and lets your gameplay do the talking. These bios are perfect for players who want to look professional and stylish without coming across as overly aggressive. They often utilize clean formatting, minimal emojis, and focus on the games you love to play.
          </p>
          <div className="bg-card border border-border rounded-xl p-6 mt-4">
            <h3 className="text-xl font-semibold text-foreground mb-3">Examples of Cool Bios:</h3>
            <ul className="space-y-2 text-foreground/80 font-mono text-sm">
              <li>✦ Casual Gamer | Just here for the vibes ✦</li>
              <li>Leveling up in real life and in-game. 🎮</li>
              <li>Weekend Warrior ⚡ Maining RPGs and FPS.</li>
              <li>Controller in hand, world tuned out. 🎧</li>
              <li>Playing games and taking names. ✨</li>
            </ul>
          </div>
        </article>

        <article className="space-y-4">
          <h2 className="text-3xl font-bold text-secondary glow-blue">Tryhard Gamer Bios</h2>
          <p className="text-foreground/90 leading-relaxed">
            If you live for ranked modes, competitive tournaments, and making opponents rage quit, you need a tryhard bio. These bios are intimidating, confident, and often feature aggressive quotes. They pair perfectly with a sweaty username and let everyone in the lobby know you mean business.
          </p>
          <div className="bg-card border border-border rounded-xl p-6 mt-4">
            <h3 className="text-xl font-semibold text-foreground mb-3">Examples of Tryhard Bios:</h3>
            <ul className="space-y-2 text-foreground/80 font-mono text-sm">
              <li>★ Ranked Demon ★ | No excuses, just results. 💀</li>
              <li>If you're reading this, you're already in my crosshairs. 🎯</li>
              <li>Esports Athlete 🏆 | Victory is the only option.</li>
              <li>Grinding to the top. Fear the unseen. ⚔️</li>
              <li>I carry my team heavier than my groceries. 🔥</li>
            </ul>
          </div>
        </article>

        <article className="space-y-4">
          <h2 className="text-3xl font-bold text-accent glow-cyan">Funny Gamer Bios</h2>
          <p className="text-foreground/90 leading-relaxed">
            Not everyone takes gaming too seriously. If you're the designated team clown or just play to have a good time with friends, a funny bio is the way to go. Self-deprecating humor about your aim, ping, or carry-ability is always a hit on platforms like Discord and Instagram.
          </p>
          <div className="bg-card border border-border rounded-xl p-6 mt-4">
            <h3 className="text-xl font-semibold text-foreground mb-3">Examples of Funny Bios:</h3>
            <ul className="space-y-2 text-foreground/80 font-mono text-sm">
              <li>My aim is potato, but my heart is gold. 🥔</li>
              <li>Professional respawner. ♻️</li>
              <li>I play on mute so I don't hear the haters (and my mom). 🤫</li>
              <li>Lag is my only enemy. (And my lack of skill). 📶</li>
              <li>Currently hiding in a bush. 🌳</li>
            </ul>
          </div>
        </article>

        <AdPlaceholder position="banner" />

        <article className="space-y-4">
          <h2 className="text-3xl font-bold text-primary">Aesthetic Gamer Bios</h2>
          <p className="text-foreground/90 leading-relaxed">
            Aesthetic bios are all about the vibe. They use specific symbols (like moons, stars, and sparkles), lowercase text, and poetic phrases. These are incredibly popular in communities like Roblox, Minecraft, and among cozy gamers or VTubers.
          </p>
          <div className="bg-card border border-border rounded-xl p-6 mt-4">
            <h3 className="text-xl font-semibold text-foreground mb-3">Examples of Aesthetic Bios:</h3>
            <ul className="space-y-2 text-foreground/80 font-mono text-sm">
              <li>🌙 lost in the digital world 🌙</li>
              <li>pixelated dreams & neon nights 🖤</li>
              <li>✧ chasing high scores and good vibes ✧</li>
              <li>cyber reality ~ plug in and tune out 🎧</li>
              <li>☁️ cozy games only ☁️</li>
            </ul>
          </div>
        </article>

        <article className="space-y-4">
          <h2 className="text-3xl font-bold text-secondary glow-blue">Platform Specific Bios</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-4">
            <div className="bg-card border border-border rounded-xl p-6">
              <h3 className="text-xl font-bold text-indigo-400 mb-2">Discord Bios</h3>
              <p className="text-foreground/80 text-sm mb-4">Discord bios should be short and formatted with line breaks. Use our 'Medium' length setting for the perfect Discord About Me section.</p>
              <Link to="/stylish-text-generator" className="text-sm text-primary hover:underline">Pro tip: Use stylish fonts &rarr;</Link>
            </div>
            
            <div className="bg-card border border-border rounded-xl p-6">
              <h3 className="text-xl font-bold text-purple-500 mb-2">Twitch Bios</h3>
              <p className="text-foreground/80 text-sm mb-4">Twitch bios need to tell viewers what you play and when you stream. Use our 'Long' setting to generate detailed panels for your channel.</p>
              <Link to="/clan-name-generator" className="text-sm text-secondary hover:underline">Need a team name? &rarr;</Link>
            </div>
          </div>
        </article>

        <article className="space-y-4">
          <h2 className="text-3xl font-bold text-accent glow-cyan">How to Write a Great Gamer Bio</h2>
          <div className="bg-card border border-border rounded-xl p-6 space-y-4">
            <ol className="list-decimal list-inside space-y-3 text-foreground/90">
              <li><strong>Know your audience:</strong> Are you trying to recruit for a sweaty clan, or just make friends? Choose your tone accordingly.</li>
              <li><strong>State your main games:</strong> Let people know if you're a Valorant demon or a cozy Stardew Valley player.</li>
              <li><strong>Use formatting:</strong> Break up text with symbols (|, -, ★) or line breaks to make it readable.</li>
              <li><strong>Add a Call to Action:</strong> End with "DM to play" or "Drop a follow" if you're a creator.</li>
              <li><strong>Keep it updated:</strong> Change your bio when you switch main games or hit a new rank.</li>
            </ol>
          </div>
        </article>

        {/* FAQ Section */}
        <article className="space-y-8 bg-card border border-border rounded-2xl p-8 shadow-lg">
          <h2 className="text-3xl font-bold text-foreground flex items-center gap-3">
            Frequently Asked Questions
          </h2>
          
          <div className="grid gap-6">
            {faqSchema.mainEntity.map((faq, idx) => (
              <div key={idx} className="space-y-2 border-b border-border/50 pb-6 last:border-0 last:pb-0">
                <h3 className="text-xl font-semibold text-primary">{faq.name}</h3>
                <p className="text-foreground/80 leading-relaxed">{faq.acceptedAnswer.text}</p>
              </div>
            ))}
          </div>
        </article>
      </section>
    </>
  );
};

export default GamerBioSEOContent;